### ISSUE TITLE
播放器不显示歌词

### ISSUE THREAD

**Issue by zlk-sys** [imsyy/home#206]
### 站点链接

zenglingkun.cn

### 问题描述

播放器不显示歌词

### 补充信息

![image](https://github.com/imsyy/home/assets/76240341/cc29280b-063b-4201-8502-a989505091d6)
使用的自建音乐API，其他的都没问题，就是不显示歌词

**Comment by zlk-sys** [comment]
每播放一首歌，console就报：
index-e12f3afb.js:8 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchLrc (index-e12f3afb.js:8:72960)
    at Proxy.applyLrc (index-e12f3afb.js:8:72897)
    at Proxy.handler (index-e12f3afb.js:8:73172)
    at Ht (index-e12f3afb.js:1:14246)
    at Wt (index-e12f3afb.js:1:14324)
    at x (index-e12f3afb.js:1:23444)
    at an (index-e12f3afb.js:1:15367)
    at D (index-e12f3afb.js:1:50501)
    at he.fn (index-e12f3afb.js:1:48751)
    at he.run (index-e12f3afb.js:1:5346)
本地环境也这样

**Comment by imsyy** [comment]
检查下你的音乐 api 服务
