### ISSUE TITLE
.env里的配置都识别不到好像是

### ISSUE THREAD

**Issue by wx-1124** [imsyy/home#328]
### 站点链接

nanshengwx.cn

### 补充信息

(!) %VITE_SITE_LOGO% is not defined in env variables found in /index.html. Is the variable mistyped?
(!) %VITE_SITE_APPLE_LOGO% is not defined in env variables found in /index.html. Is the variable mistyped?
(!) %VITE_SITE_APPLE_LOGO% is not defined in env variables found in /index.html. Is the variable mistyped? (x2)
(!) %VITE_SITE_APPLE_LOGO% is not defined in env variables found in /index.html. Is the variable mistyped? (x3)
(!) %VITE_SITE_DES% is not defined in env variables found in /index.html. Is the variable mistyped?
(!) %VITE_SITE_KEYWORDS% is not defined in env variables found in /index.html. Is the variable mistyped?
(!) %VITE_SITE_AUTHOR% is not defined in env variables found in /index.html. Is the variable mistyped?
(!) %VITE_SITE_NAME% is not defined in env variables found in /index.html. Is the variable mistyped?
16:54:19 [vite] Internal server error: URI malformed
      at decodeURI (<anonymous>)
      at viteTransformMiddleware (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:64318:19)
      at call (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:50689:7)
      at next (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:50633:5)
      at file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47527:28
      at viteServePublicMiddleware (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:47657:9)
      at call (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:50689:7)
      at next (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:50633:5)
      at viteHMRPingMiddleware (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65285:13)
      at call (file:///D:/kaifa/workspace/demo/home1/home/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:50689:7)

**Comment by wx-1124** [comment]
![Snipaste_2024-07-25_17-41-49](https://github.com/user-attachments/assets/7e3dd16a-8f9b-4945-a471-cfb791214e96)
这个注释掉没报错了，但env里的数据还是没映射进去

**Comment by wx-1124** [comment]
看到文档了，要重命名，不好意思啊
